run:
  build-tags: []
  skip-dirs: []
  skip-files: []
 
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
 
linters:
  enable-all: true
  disable:
    - interfacer
    - maligned
    - scopelint
    - golint
    - wrapcheck
    - varnamelen
    - tagliatelle
    - stylecheck
    - nlreturn
    - gomnd
    - gochecknoglobals
    - forcetypeassert
    - revive
    - ireturn
    - godox
    - forbidigo
    - gci
    - noctx
    - wsl
    - godot
 
linters-settings:
  govet:
    check-shadowing: true
 
  gocyclo:
    min-complexity: 15
 
  lll:
    line-length: 150
    tab-width: 4
 
  nakedret:
    max-func-lines: 10
 
  funlen:
    lines: 50
    statements: 40
 
issues:
  exclude: []
  exclude-rules:
    - path: _test.go
      linters:
        - lll
        - funlen
        - dupl
    - linters:
      - errcheck
      source: "defer .*Rollback()"
    - linters:
      - errcheck
      source: "defer .*Close()"
    - linters:
      - exhaustivestruct
      text: "Core is missing"
    - linters:
      - exhaustivestruct
      source: "\\{\\}"
    - linters:
      - typecheck
      text: "could not import syscall/js"

  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
