version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - godot
    - godox
    - ireturn
    - nlreturn
    - noctx
    - paralleltest
    - revive
    - tagliatelle
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
    - depguard
    - lll
    - rowserrcheck
    - mnd
    - interfacebloat
    - inamedparam
    - funcorder
    - noinlineerr
    - wsl_v5
    - funlen
    - nestif
    - cyclop
  settings:
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 150
      tab-width: 4
    nakedret:
      max-func-lines: 10
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - funlen
          - lll
        path: _test.go
      - linters:
          - testpackage
        path: backend/application/order/order_test.go
      - linters:
          - errcheck
        source: defer .*Rollback()
      - linters:
          - errcheck
        source: defer .*Close()
    paths:
      - _vgen.go$
      - migratelegacydb
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - _vgen.go$
      - migratelegacydb
      - third_party$
      - builtin$
      - examples$
